### ISSUE TITLE
Curious use of h64 immediately truncated down to 32 bits

### ISSUE THREAD

**Issue by SimonWoolf** [kblauhut/bl00mer#3]
The package is currently doing `XXH.h64(...)`, then taking the result and calling `toNumber()` on it. This [drops the most significant 32 bits](https://github.com/pierrec/js-cuint/blob/b93425a8f1b98bab8e357cede34ed491125c0d8b/lib/uint64.js#L143), giving you effectively the same result as if you'd just used `XXH.h32(...)` instead of `h64` (maybe even the exact same output if one is an extension of the other in xxhash). I don't think this is a big problem - 32 bits should still be enough entropy - but it does look kindof odd; wondering if it's intentional, and if so what the reason is?

(Sidenote: thankyou for making this! :blush: Nice implementation. It's very strange that the most widely used JS bloom filter implementation uses one number per bit, insanely wasteful given the whole point of bloom filters is to be space-efficient)

**Comment by kblauhut** [comment]
Nice catch :D 
Yeah this seems to indeed not be using 64 bits and I assume 32 bits is fine for this as well.

This package was actually made for the luca app which is a german covid tracing app. We needed an efficient bloom filter implementation for anonymous data retrieval. Sadly the only js bloom filter implementation I could find was extremely inefficient since it used a js number instead of 1 bit (so 64 times the memory)
