### ISSUE TITLE
Double-hashing bug introduced in 1.2

### ISSUE THREAD

**Issue by SimonWoolf** [kblauhut/bl00mer#4]
https://github.com/kblauhut/bloomit/blob/150007566a29cdc0ce2e70488f9075e89a3522b1/src/utils.ts#L109 (changed in https://github.com/kblauhut/bloomit/pull/2/files#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R109 ) changed the double hashing algorithm from `(h₁ + ih₂) mod m` to `(h₁ + i + h₂) mod m`. This is a curious change. The result is no longer double hashing. Sequential `i`s will now produce sequential indices, since you're just adding the index on each loop.

This is partially ameliorated by your adding `size % n` (incidentally, why modulo the loop iteration? that makes no sense) to the seed on each loop iteration and rehashing -- but you shouldn'd need to do that with double hashing, the point is you can just calculate two hashes and then use those, if you're rehashing on every loop iteration anyway then double hashing isn't actually buying you anything. But I realise that that at least was just inherited from the `bloom-filters` package.

**Comment by SimonWoolf** [comment]
(fyi: I forked and fixed as https://github.com/ably-forks/bloomit , and made some other changes, happy to do a PR to here if there's anything you'd like contributed back. I suspect you'd prefer to stick to XXH so I can do a version that sticks with that?)

**Comment by kblauhut** [comment]
This is indeed a problem and as a matter of fact also known by me. This version should have never been released and is actually not used in production.
I forgot to release a new version that reverts the change.

The reason this was initially implemented is because there is a possibility to crash the bloom filter with endless recursion with certain input. (See the tests written in the 1.2 release)
